version: '3'
services:
  nginx:
    image: nginx:1.15-alpine
    container_name: common-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /mnt/hgfs/docker/nginx/conf/conf.d:/etc/nginx/conf.d
      - /mnt/hgfs/docker/nginx/conf/ssl:/etc/nginx/ssl
      - /mnt/hgfs/docker/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - /mnt/hgfs/www:/usr/share/nginx/html
      - /mnt/hgfs/docker/logs/nginx/:/var/log/nginx
    environment:
      - TZ=Asia/Shanghai
    networks:
      - baidu_nginx_net
    depends_on:
      - commonphp
  commonphp:
    image: registry.cn-hangzhou.aliyuncs.com/xuweiguo/5.4-fpm:0.0.9
    container_name: common-php
    ports:
      - 9000
    volumes:
      - /mnt/hgfs/www:/usr/share/nginx/html:rw
      - /mnt/hgfs/docker/logs/php/:/var/log/php:rw
      - /mnt/hgfs/docker/php/conf/php/conf.d/php.ini:/usr/local/etc/php/conf.d/php.ini:ro
      - /mnt/hgfs/docker/php/conf/php-fpm.d:/usr/local/etc/php-fpm.d:ro
    environment:
      - TZ=Asia/Shanghai
    networks:
      - baidu_nginx_net
    extra_hosts:
      - verify.mini.test.com:192.168.0.234
      - verify.mini.local:192.168.99.100
      - check.test.com:192.168.0.234
      - www.verify.cn:192.168.1.5
      - www.verify_system.cn:192.168.1.5
    depends_on:
      -  commonredis
  commonredis:
    image: redis:3.2
    container_name: common-redis
    ports:
      - 6379
    networks:
      - baidu_nginx_net
networks:
  baidu_nginx_net:
